version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - './volumes/mongo:/data/db'


  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'